/**
 * The CMS's generated parts: the named option sets its dropdowns choose
 * from, and the served config.
 *
 * Every reference in the model is an ID. src/cms/config.yml names a set
 * where a field takes one (`options: "@records"`), and this fills each set
 * from the model, labelled, so the dropdown shows names and saves the ID.
 */
import { parseDocument } from "yaml";
import { loadModel, spans } from "./model.ts";

export type Option = { label: string; value: string };

const clip = (text: string, n = 70) => {
  const t = text.replace(/\s+/g, " ").trim();
  return t.length > n ? `${t.slice(0, n - 1).trimEnd()}…` : t;
};

/** The named sets src/cms/config.yml may use. */
export function optionSets(base: URL): Record<string, Option[]> {
  const model = loadModel(base);
  const byId = (a: { id: string }, b: { id: string }) =>
    a.id.localeCompare(b.id, "en", { numeric: true });
  return {
    "@records": [...model.records]
      .sort(byId)
      .map((r) => ({ label: `${r.id} · ${r.kind} — ${clip(r.title, 60)}`, value: r.id })),
    "@entities": [...model.entities]
      .sort((a, b) => a.kind.localeCompare(b.kind) || a.label.localeCompare(b.label))
      .map((e) => ({ label: `${e.kind} · ${e.label}`, value: e.id })),
    "@evidence": model.evidence.map((l) => ({
      label: `${l.id} · ${l.type} · ${l.record}`,
      value: l.id,
    })),
    "@text": [...spans(model.records)].map(([key, text]) => ({
      label: `${key} — ${clip(text || "(no caption)", 60)}`,
      value: key,
    })),
  };
}

const HEADER = `# Generated by scripts/cms-build.ts from src/cms/config.yml, on every
# dev start and build. Don't edit this file: edit src/cms/config.yml.
`;

/**
 * The served config: src/cms/config.yml with every `options: "@set"`
 * filled in. Throws on a set it doesn't know, so a typo fails the build.
 * The CMS refuses a dropdown with no options, so while a set is empty (an
 * empty museum) its field is a plain text box, or a list of them.
 */
export function buildConfig(source: string, base: URL): string {
  const doc = parseDocument(source);
  const sets = optionSets(base);
  const visit = (node: unknown): unknown => {
    if (Array.isArray(node)) return node.map(visit);
    if (!node || typeof node !== "object") return node;
    const field = node as Record<string, unknown>;
    const set = field.options;
    if (typeof set === "string" && set.startsWith("@")) {
      if (!sets[set]) throw new Error(`src/cms/config.yml: no option set ${set}`);
      if (sets[set].length) return { ...field, options: sets[set] };
      const { options: _options, multiple, widget: _widget, min: _min, ...rest } = field;
      return multiple
        ? { ...rest, widget: "list", field: { name: "id", label: "ID", widget: "string" } }
        : { ...rest, widget: "string" };
    }
    return Object.fromEntries(Object.entries(field).map(([k, v]) => [k, visit(v)]));
  };
  const filled = visit(doc.toJS({ maxAliasCount: -1 }));
  return HEADER + JSON.stringify(filled, null, 2) + "\n";
}
