/**
 * The museum's model, as this repository holds it. Generated by `mw init`;
 * the universal collections only.
 *
 *   src/model/records/<id>.json     one per image or document
 *   src/model/entities/<slug>.json  people, places, ...: each anchored
 *   src/model/questions/<id>.json   bounded open questions
 *   src/model/evidence.json         claims linked to records
 *   src/data/corrections/<id>.json  the queue: text corrections and name proposals
 *   meta/sequences.json             IDs claimed, by input hash
 *   meta/tombstones.json            IDs retired, never reissued
 */
import { readFolder, readJson } from "./files.ts";

export type Passage = { id: string; text: string };

/** Where a record (or a proposal) came from, when `mw` wrote it. */
export type Source = {
  url?: string;
  file?: string;
  file_url?: string;
  page?: number;
  model?: string;
  extracted_at?: string;
  input_hash?: string;
  tool?: string;
};

export type RecordNote = { date: string; note: string };

export type MuseumRecord = {
  id: string;
  kind: "image" | "document" | "object" | "log";
  title: string;
  /** Verbatim, or empty. Never invented. */
  caption?: string;
  credit?: string;
  alt?: string;
  /** The record (a page, a PDF) it was found in. */
  found_in?: string;
  position?: number;
  follows?: string;
  passages?: Passage[];
  rights_holder?: string;
  held: boolean;
  status: "verified" | "unverified" | "not-held";
  media?: string[];
  source?: Source;
  capture_provenance?: Record<string, string>;
  notes?: RecordNote[];
};

export const ENTITY_KINDS = ["person", "family", "place", "organization", "event"] as const;
export type EntityKind = (typeof ENTITY_KINDS)[number];

export type Entity = {
  id: string;
  slug: string;
  kind: EntityKind;
  label: string;
  aliases?: { name: string; sources?: string[] }[];
  anchors?: string[];
  notes?: RecordNote[];
};

export type OpenQuestion = {
  id: string;
  title: string;
  what_we_know: string;
  what_we_dont: string;
  what_might_answer_it: string;
  evidence_needed: string;
  last_known_source?: string[];
  entities?: string[];
  status: "open" | "answered";
  evidence?: string[];
  curator: string;
  date: string;
};

export type EvidenceLink = {
  id: string;
  claim: { span: string; quote: string };
  record: string;
  type: "supports" | "contradicts" | "qualifies";
  note?: string;
  curator: string;
  date: string;
};

export type Correction = {
  id: string;
  /** "text" (the default): the span as it should read, whole. "name": a name the span spells. */
  kind?: "text" | "name";
  /** A span: "<record>#<passage>" or "plate:<record>". */
  target: string;
  proposed_text: string;
  entity_kind?: EntityKind;
  reason: string;
  proposed_by: string;
  date: string;
  status: "proposed" | "accepted" | "applied" | "rejected" | "held";
  decided_by?: string;
  decided_on?: string;
  curator_note?: string;
  source?: Source;
};

export type Sequence = { prefix: string; width: number; next: number };
export type Sequences = { record: Sequence; correction: Sequence; claims: Record<string, string> };
export type Tombstone = { id: string; date: string; reason: string };

export type Museum = {
  slug: string;
  title: string;
  rights_holder: string;
  status: string;
  text_freeze: boolean;
  schema_version: number;
};

export type Model = ReturnType<typeof loadModel>;

/** The whole model, read from the repository at `base`, with each file's name kept for the file-name checks. */
export function loadModel(base: URL) {
  const files = {
    records: readFolder(base, "src/model/records") as { file: string; data: MuseumRecord }[],
    entities: readFolder(base, "src/model/entities") as { file: string; data: Entity }[],
    questions: readFolder(base, "src/model/questions") as { file: string; data: OpenQuestion }[],
    corrections: readFolder(base, "src/data/corrections") as { file: string; data: Correction }[],
  };
  return {
    museum: readJson<Museum | null>(base, "src/model/museum.json", null),
    files,
    records: files.records.map((f) => f.data),
    entities: files.entities.map((f) => f.data),
    questions: files.questions.map((f) => f.data),
    corrections: files.corrections.map((f) => f.data),
    evidence: readJson<EvidenceLink[]>(base, "src/model/evidence.json", []),
    sequences: readJson<Sequences | null>(base, "meta/sequences.json", null),
    tombstones: readJson<Tombstone[] | null>(base, "meta/tombstones.json", null),
  };
}

/** Every span's words, by key: each passage ("r-0001#p3") and each record's caption ("plate:r-0002"). */
export function spans(records: MuseumRecord[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const r of records) {
    for (const p of r.passages ?? []) out.set(`${r.id}#${p.id}`, p.text);
    if (r.kind === "image" || r.caption) out.set(`plate:${r.id}`, r.caption ?? "");
  }
  return out;
}

/** The record a span belongs to. */
export const spanRecord = (key: string) =>
  key.startsWith("plate:") ? key.slice(6) : key.split("#")[0];

/** All of a record's own words: title, caption, credit, alt text and passages. */
export const recordText = (r: MuseumRecord) =>
  [r.title, r.caption ?? "", r.credit ?? "", r.alt ?? "", ...(r.passages ?? []).map((p) => p.text)].join(
    "\n",
  );
