import { spawn, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, statSync, symlinkSync } from "node:fs";
import { createServer, type Server } from "node:http";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export const MW = fileURLToPath(new URL("../bin/mw.mjs", import.meta.url));
const TOOL_MODULES = fileURLToPath(new URL("../node_modules/", import.meta.url));

export const tmp = (name: string) => mkdtempSync(join(tmpdir(), `mw-${name}-`));

/** Runs mw without blocking this process, which may be serving the page and the model it calls. */
export function mw(args: string[], env: Record<string, string> = {}): Promise<{ code: number | null; out: string }> {
  return new Promise((ok) => {
    const child = spawn(process.execPath, [MW, ...args], {
      env: { ...process.env, MW_NOW: "2026-10-04T12:00:00Z", ...env },
    });
    let out = "";
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (out += d));
    child.on("close", (code) => ok({ code, out }));
  });
}

function mwSync(args: string[]) {
  const r = spawnSync(process.execPath, [MW, ...args], { encoding: "utf8" });
  return { code: r.status, out: r.stdout + r.stderr };
}

/** A fresh museum, generated by mw init, with the tool's yaml linked in so the CMS build runs offline. */
export function freshMuseum(name = "test-museum"): string {
  const dir = join(tmp(name), name);
  const r = mwSync(["init", name, "--repo", `someone/${name}`, "--dir", dir, "--no-install", "--no-git"]);
  if (r.code !== 0) throw new Error(r.out);
  mkdirSync(join(dir, "node_modules"), { recursive: true });
  symlinkSync(join(TOOL_MODULES, "yaml"), join(dir, "node_modules/yaml"));
  return dir;
}

export function run(dir: string, script: string) {
  const r = spawnSync(process.execPath, ["--experimental-strip-types", "--no-warnings=ExperimentalWarning", script], { cwd: dir, encoding: "utf8" });
  return { code: r.status, out: r.stdout + r.stderr };
}

export const readJson = (path: string) => JSON.parse(readFileSync(path, "utf8"));
export const jsonIn = (dir: string) =>
  readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => readJson(join(dir, f)));

/** Every file under dir (but node_modules and the generated config), with its hash: to show a re-run changed nothing. */
export function tree(dir: string): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (d: string) => {
    for (const f of readdirSync(d)) {
      const p = join(d, f);
      if (f === "node_modules" || p.endsWith("public/admin/config.yml") || p.includes("public/data")) continue;
      if (statSync(p).isDirectory()) walk(p);
      else out[relative(dir, p)] = createHash("sha256").update(readFileSync(p)).digest("hex");
    }
  };
  walk(dir);
  return out;
}

export async function serve(routes: Map<string, { type: string; body: Uint8Array | string }>): Promise<{ url: string; server: Server; hits: string[] }> {
  const hits: string[] = [];
  const server = createServer((req, res) => {
    const path = new URL(req.url ?? "/", "http://x").pathname;
    hits.push(path);
    const r = routes.get(path);
    if (!r) return res.writeHead(404).end();
    res.writeHead(200, { "content-type": r.type }).end(r.body);
  });
  await new Promise<void>((ok) => server.listen(0, "127.0.0.1", ok));
  const addr = server.address() as { port: number };
  return { url: `http://127.0.0.1:${addr.port}`, server, hits };
}

/**
 * A stand-in for llama-server, for tests: it answers /health, /props and
 * /completion, and "notices" every name from its list that the passage
 * contains, plus one it doesn't (which the span rule must drop), and one
 * misspelled.
 */
export async function stubModel(names: [string, string][]): Promise<{ url: string; server: Server; prompts: string[] }> {
  const prompts: string[] = [];
  const server = createServer((req, res) => {
    let body = "";
    req.on("data", (c) => (body += c));
    req.on("end", () => {
      const path = new URL(req.url ?? "/", "http://x").pathname;
      if (path === "/health") return res.writeHead(200, { "content-type": "application/json" }).end('{"status":"ok"}');
      if (path === "/props") return res.writeHead(200, { "content-type": "application/json" }).end('{"model_path":"/models/Qwen3-1.7B-Q4_K_M.gguf"}');
      if (path !== "/completion") return res.writeHead(404).end();
      const { prompt, grammar } = JSON.parse(body);
      if (!grammar) return res.writeHead(400).end("no grammar");
      prompts.push(prompt);
      const passage = prompt.split("Passage:\n")[1]?.split("<|im_end|>")[0] ?? "";
      const found = names.filter(([n]) => passage.includes(n)).map(([name, kind]) => ({ name, kind }));
      if (found.length) found.push({ name: "Josephine Bonaparte", kind: "person" }, { name: found[0].name.toUpperCase() + "X", kind: found[0].kind });
      res.writeHead(200, { "content-type": "application/json" }).end(JSON.stringify({ content: JSON.stringify({ names: found }) }));
    });
  });
  await new Promise<void>((ok) => server.listen(0, "127.0.0.1", ok));
  return { url: `http://127.0.0.1:${(server.address() as { port: number }).port}`, server, prompts };
}
