/**
 * The CMS's generated parts: the named option sets its dropdowns choose
 * from, the served config, and the ID key page.
 *
 * Every reference in the model is an ID: an entity's eight hex characters,
 * a record's, a passage's, an evidence link's. src/cms/config.yml names a set
 * where a field takes one (`options: "@entities"`), and this fills each set
 * from the model, labelled and grouped ("Person · Joyce B. Calicura"), so the
 * dropdown shows names and saves the ID. Generated on every dev start and
 * build, so a new entry is in the lists without anyone editing the config.
 */
import { parseDocument } from "yaml";
import { ingestedChapters } from "../../src/data/chapters.ts";
import { corrections, textKeys } from "../../src/data/corrections.ts";
import { discrepancies } from "../../src/data/discrepancies.ts";
import { ingestedPhotos, photoList } from "../../src/data/photos.ts";
import { entities, evidence, records } from "../../src/model/index.ts";
import { ENTITY_KINDS, SERIES } from "../../src/model/types.ts";

export type Option = { label: string; value: string };

const clip = (text: string, n = 70) => {
  const t = text.replace(/\s+/g, " ").trim();
  return t.length > n ? `${t.slice(0, n - 1).trimEnd()}…` : t;
};

const kindRank = new Map<string, number>(ENTITY_KINDS.map(([k], i) => [k, i]));
const kindLabel = new Map<string, string>(ENTITY_KINDS.map(([k, one]) => [k, one]));
const seriesRank = new Map<string, number>(SERIES.map(([s], i) => [s, i]));
const seriesLabel = new Map<string, string>(SERIES.map(([s, label]) => [s, label]));

/** Entities by kind, then missions by number and the rest by name. */
export function entityOptions(): Option[] {
  return [...entities]
    .sort(
      (a, b) =>
        (kindRank.get(a.kind) ?? 99) - (kindRank.get(b.kind) ?? 99) ||
        (a.mission ?? 0) - (b.mission ?? 0) ||
        a.label.localeCompare(b.label),
    )
    .map((e) => ({ label: `${kindLabel.get(e.kind) ?? e.kind} · ${e.label}`, value: e.id }));
}

/** Records by series, as the personnel file keeps them, then by ID. */
export function recordOptions(): Option[] {
  return [...records]
    .sort(
      (a, b) =>
        (seriesRank.get(a.series) ?? 99) - (seriesRank.get(b.series) ?? 99) ||
        a.id.localeCompare(b.id, "en", { numeric: true }),
    )
    .map((r) => ({
      label: `${seriesLabel.get(r.series) ?? r.series} · ${r.id} — ${clip(r.title, 60)}`,
      value: r.id,
    }));
}

/** The series, by their labels. */
export function seriesOptions(): Option[] {
  return SERIES.map(([value, label]) => ({ label, value }));
}

/** Chapters, in reading order. */
export function chapterOptions(): Option[] {
  return ingestedChapters.map((c) => ({ label: `${c.number}. ${c.title}`, value: c.slug }));
}

/** Plates, in catalog order. */
export function plateOptions(): Option[] {
  return photoList.map((p, i) => ({
    label: `Plate ${i + 1} · ${p.id} — ${clip(p.title, 60)}`,
    value: p.id,
  }));
}

/**
 * Everything a correction can target: each paragraph, quote and note in
 * reading order, by chapter, then each plate's caption.
 */
export function textOptions(): Option[] {
  const chapterTitle = new Map(ingestedChapters.map((c) => [c.slug, `${c.number}. ${c.title}`]));
  return [...textKeys(ingestedChapters, ingestedPhotos)].map(([key, text]) => {
    if (key.startsWith("plate:"))
      return { label: `Caption · ${key.slice(6)} — ${clip(text, 60)}`, value: key };
    const [slug, id] = key.split("#");
    return { label: `${chapterTitle.get(slug)} · ${id} — ${clip(text, 60)}`, value: key };
  });
}

/** Evidence links, by ID. */
export function evidenceOptions(): Option[] {
  return evidence.map((l) => ({
    label: `${l.id} · ${l.type} · ${l.record}${l.note ? ` — ${clip(l.note, 50)}` : ""}`,
    value: l.id,
  }));
}

/** The Both Stand register's entries. */
export function registerOptions(): Option[] {
  return discrepancies.map((d) => ({ label: `${d.title} (${d.id})`, value: d.id }));
}

export function correctionOptions(): Option[] {
  return corrections.map((c) => ({ label: `${c.id} · ${c.target} · ${c.status}`, value: c.id }));
}

/** The named sets src/cms/config.yml may use. */
export function optionSets(): Record<string, Option[]> {
  return {
    "@entities": entityOptions(),
    "@records": recordOptions(),
    "@series": seriesOptions(),
    "@chapters": chapterOptions(),
    "@plates": plateOptions(),
    "@text": textOptions(),
    "@evidence": evidenceOptions(),
    "@register": registerOptions(),
    "@corrections": correctionOptions(),
  };
}

const HEADER = `# Generated by scripts/cms-build.ts from src/cms/config.yml, on every
# dev start and build. Don't edit this file: edit src/cms/config.yml.
`;

/**
 * The served config: src/cms/config.yml with every `options: "@set"`
 * filled in. Throws on a set it doesn't know, so a typo fails the build.
 * The CMS refuses a dropdown with no options, so while a set is empty (no
 * corrections yet) its field is a plain text box, or a list of them, until
 * the set has something in it.
 */
export function buildConfig(source: string): string {
  const doc = parseDocument(source);
  const sets = optionSets();
  const visit = (node: unknown): unknown => {
    if (Array.isArray(node)) return node.map(visit);
    if (!node || typeof node !== "object") return node;
    const field = node as Record<string, unknown>;
    const set = field.options;
    if (typeof set === "string" && set.startsWith("@")) {
      if (!sets[set]) throw new Error(`src/cms/config.yml: no option set ${set}`);
      if (sets[set].length) return { ...field, options: sets[set] };
      const { options: _options, multiple, widget: _widget, ...rest } = field;
      return multiple
        ? { ...rest, widget: "list", field: { name: "id", label: "ID", widget: "string" } }
        : { ...rest, widget: "string" };
    }
    return Object.fromEntries(Object.entries(field).map(([k, v]) => [k, visit(v)]));
  };
  const filled = visit(doc.toJS({ maxAliasCount: -1 }));
  return HEADER + JSON.stringify(filled, null, 2) + "\n";
}

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/**
 * The ID key: every entity by kind, with its ID, its slug and what anchors
 * it. For reading the raw files and the CMS's pull requests, where the IDs
 * are all that shows.
 */
export function keyPage(): string {
  const sections = ENTITY_KINDS.flatMap(([kind, , plural]) => {
    const list = entities
      .filter((e) => e.kind === kind)
      .sort((a, b) => (a.mission ?? 0) - (b.mission ?? 0) || a.label.localeCompare(b.label));
    if (!list.length) return [];
    const rows = list
      .map(
        (e) =>
          `<tr id="${e.id}"><td>${esc(e.label)}</td><td><code>${e.id}</code></td><td><code>${e.slug}</code></td><td>${e.anchors.length}</td></tr>`,
      )
      .join("\n");
    return [
      `<h2>${plural} <span>${list.length}</span></h2>\n<table><thead><tr><th>Name</th><th>ID</th><th>Slug</th><th>Anchors</th></tr></thead><tbody>\n${rows}\n</tbody></table>`,
    ];
  });
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<title>ID key · The Spirit of Martinez</title>
<style>
  :root { color-scheme: light dark; --ink: #141210; --muted: #7a7366; --rule: #e7d9bc; --bg: #f3ead6; --accent: #8e3a32; }
  @media (prefers-color-scheme: dark) { :root { --ink: #f3ead6; --muted: #cfc6b2; --rule: #3a342c; --bg: #141210; --accent: #b8954a; } }
  body { margin: 0; background: var(--bg); color: var(--ink); font: 15px/1.5 system-ui, sans-serif; }
  main { max-width: 52rem; margin: 0 auto; padding: 2rem 1rem 4rem; }
  h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
  h2 { font-size: 1.05rem; margin: 2rem 0 .5rem; border-bottom: 1px solid var(--rule); padding-bottom: .25rem; }
  h2 span { color: var(--muted); font-weight: normal; }
  p { color: var(--muted); margin: 0 0 1rem; }
  table { width: 100%; border-collapse: collapse; }
  td, th { text-align: left; padding: .3rem .5rem .3rem 0; border-bottom: 1px solid var(--rule); vertical-align: top; }
  th { color: var(--muted); font-weight: normal; font-size: .85rem; }
  code { font-size: .85em; color: var(--muted); white-space: nowrap; }
  tr:target { background: color-mix(in srgb, var(--accent) 12%, transparent); }
  @media (max-width: 480px) { td:nth-child(3), th:nth-child(3), td:nth-child(4), th:nth-child(4) { display: none; } }
</style>
</head>
<body>
<main>
<h1>ID key</h1>
<p>Every entity the museum names, by kind, with the ID its files use, the slug in its address and how many records anchor it. Generated from the model on every build. Link to one as <code>/admin/key.html#${entities[0]?.id ?? ""}</code>.</p>
${sections.join("\n")}
</main>
</body>
</html>
`;
}
