/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AircraftRouteImport } from './routes/aircraft'
import { Route as BookRouteImport } from './routes/book'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as CrewIndexRouteImport } from './routes/crew.index'
import { Route as CrewIdRouteImport } from './routes/crew.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftRoute = AircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/crew/',
  path: '/crew/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIdRoute = CrewIdRouteImport.update({
  id: '/crew/$id',
  path: '/crew/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aircraft': typeof AircraftRoute
  '/book': typeof BookRoute
  '/missions': typeof MissionsRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/crew/$id': typeof CrewIdRoute
  '/archive/': typeof ArchiveIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/crew/': typeof CrewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aircraft': typeof AircraftRoute
  '/book': typeof BookRoute
  '/missions': typeof MissionsRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/crew/$id': typeof CrewIdRoute
  '/archive': typeof ArchiveIndexRoute
  '/chapters': typeof ChaptersIndexRoute
  '/crew': typeof CrewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aircraft': typeof AircraftRoute
  '/book': typeof BookRoute
  '/missions': typeof MissionsRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/crew/$id': typeof CrewIdRoute
  '/archive/': typeof ArchiveIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/crew/': typeof CrewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aircraft'
    | '/book'
    | '/missions'
    | '/sources'
    | '/timeline'
    | '/archive/$id'
    | '/chapters/$slug'
    | '/crew/$id'
    | '/archive/'
    | '/chapters/'
    | '/crew/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aircraft'
    | '/book'
    | '/missions'
    | '/sources'
    | '/timeline'
    | '/archive/$id'
    | '/chapters/$slug'
    | '/crew/$id'
    | '/archive'
    | '/chapters'
    | '/crew'
  id:
    | '__root__'
    | '/'
    | '/aircraft'
    | '/book'
    | '/missions'
    | '/sources'
    | '/timeline'
    | '/archive/$id'
    | '/chapters/$slug'
    | '/crew/$id'
    | '/archive/'
    | '/chapters/'
    | '/crew/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AircraftRoute: typeof AircraftRoute
  BookRoute: typeof BookRoute
  MissionsRoute: typeof MissionsRoute
  SourcesRoute: typeof SourcesRoute
  TimelineRoute: typeof TimelineRoute
  ArchiveIdRoute: typeof ArchiveIdRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  CrewIdRoute: typeof CrewIdRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  CrewIndexRoute: typeof CrewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft': {
      id: '/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/crew'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/$id': {
      id: '/crew/$id'
      path: '/crew/$id'
      fullPath: '/crew/$id'
      preLoaderRoute: typeof CrewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AircraftRoute: AircraftRoute,
  BookRoute: BookRoute,
  MissionsRoute: MissionsRoute,
  SourcesRoute: SourcesRoute,
  TimelineRoute: TimelineRoute,
  ArchiveIdRoute: ArchiveIdRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  CrewIdRoute: CrewIdRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  CrewIndexRoute: CrewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
